# Configuration file for landscape.io
# See https://docs.landscape.io/configuration.html

ignore-paths:
    - build/
    - dist/
    - env/
    - man/
    - test/
    - tests/

pylint:
    disable:
        - super-on-old-class
